// ═══════════════════════════════════════════════════════════
// BeUnifyT v8 — langs.js — 25 idiomas completos
// PREMISA: todos los idiomas tienen traducción propia
// ═══════════════════════════════════════════════════════════

import { AppState } from './state.js';

export const LANGS_UI = [
  { code:'es', flag:'🇪🇸', name:'Español' },
  { code:'ca', flag:'<svg width="20" height="14" viewBox="0 0 20 14" style="vertical-align:middle;border-radius:1px;border:0.5px solid #bbb"><rect width="20" height="14" fill="#FCDD09"/><rect y="1.75" width="20" height="1.75" fill="#DA121A"/><rect y="5.25" width="20" height="1.75" fill="#DA121A"/><rect y="8.75" width="20" height="1.75" fill="#DA121A"/><rect y="12.25" width="20" height="1.75" fill="#DA121A"/></svg>', name:'Català' },
  { code:'eu', flag:'<svg width="20" height="14" viewBox="0 0 20 14" style="vertical-align:middle;border-radius:1px;border:0.5px solid #bbb"><rect width="20" height="14" fill="#D52B1E"/><rect x="8" width="4" height="14" fill="#007A3D"/><rect y="5" width="20" height="4" fill="#007A3D"/><line x1="0" y1="0" x2="20" y2="14" stroke="#FFF" stroke-width="2.5"/><line x1="20" y1="0" x2="0" y2="14" stroke="#FFF" stroke-width="2.5"/><rect x="8" width="4" height="14" fill="#007A3D"/><rect y="5" width="20" height="4" fill="#007A3D"/></svg>', name:'Euskara' },
  { code:'gl', flag:'<svg width="20" height="14" viewBox="0 0 20 14" style="vertical-align:middle;border-radius:1px;border:0.5px solid #bbb"><rect width="20" height="14" fill="#FFF"/><polygon points="0,0 5,0 20,14 15,14" fill="#00A2E2"/></svg>', name:'Galego' },
  { code:'en', flag:'🇬🇧', name:'English' },
  { code:'fr', flag:'🇫🇷', name:'Français' },
  { code:'de', flag:'🇩🇪', name:'Deutsch' },
  { code:'it', flag:'🇮🇹', name:'Italiano' },
  { code:'pt', flag:'🇵🇹', name:'Português' },
  { code:'pl', flag:'🇵🇱', name:'Polski' },
  { code:'ro', flag:'🇷🇴', name:'Română' },
  { code:'nl', flag:'🇳🇱', name:'Nederlands' },
  { code:'hu', flag:'🇭🇺', name:'Magyar' },
  { code:'cs', flag:'🇨🇿', name:'Čeština' },
  { code:'hr', flag:'🇭🇷', name:'Hrvatski' },
  { code:'uk', flag:'🇺🇦', name:'Українська' },
  { code:'ru', flag:'🇷🇺', name:'Русский' },
  { code:'tr', flag:'🇹🇷', name:'Türkçe' },
  { code:'ar', flag:'🇸🇦', name:'العربية' },
  { code:'sv', flag:'🇸🇪', name:'Svenska' },
  { code:'fi', flag:'🇫🇮', name:'Suomi' },
  { code:'el', flag:'🇬🇷', name:'Ελληνικά' },
  { code:'bg', flag:'🇧🇬', name:'Български' },
  { code:'sk', flag:'🇸🇰', name:'Slovenčina' },
  { code:'sl', flag:'🇸🇮', name:'Slovenščina' },
];

// ═══════════════════════════════════════════════════════════
// DICCIONARIOS — 25 idiomas por módulo
// ═══════════════════════════════════════════════════════════

const DICT = {

// ── SHELL ────────────────────────────────────────────────
shell: {
  es:{logout:'Cerrar sesión',settings:'Ajustes',lang_ok:'Idioma guardado',search:'Buscar',noData:'Sin datos',loading:'Cargando...',error:'Error',save:'Guardar',cancel:'Cancelar',add:'Añadir',edit:'Editar',delete:'Eliminar',export:'Exportar',import:'Importar',confirm:'Confirmar',back:'Volver',close:'Cerrar',yes:'Sí',no:'No',filter:'Filtrar',all:'Todos',today:'Hoy',print:'Imprimir'},
  ca:{logout:'Tancar sessió',settings:'Ajustos',lang_ok:'Idioma desat',search:'Cercar',noData:'Sense dades',loading:'Carregant...',error:'Error',save:'Desar',cancel:'Cancel·lar',add:'Afegir',edit:'Editar',delete:'Eliminar',export:'Exportar',import:'Importar',confirm:'Confirmar',back:'Tornar',close:'Tancar',yes:'Sí',no:'No',filter:'Filtrar',all:'Tots',today:'Avui',print:'Imprimir'},
  eu:{logout:'Saioa itxi',settings:'Ezarpenak',lang_ok:'Hizkuntza gordeta',search:'Bilatu',noData:'Daturik ez',loading:'Kargatzen...',error:'Errorea',save:'Gorde',cancel:'Utzi',add:'Gehitu',edit:'Editatu',delete:'Ezabatu',export:'Esportatu',import:'Inportatu',confirm:'Berretsi',back:'Itzuli',close:'Itxi',yes:'Bai',no:'Ez',filter:'Iragazi',all:'Denak',today:'Gaur',print:'Inprimatu'},
  gl:{logout:'Pechar sesión',settings:'Axustes',lang_ok:'Idioma gardado',search:'Buscar',noData:'Sen datos',loading:'Cargando...',error:'Erro',save:'Gardar',cancel:'Cancelar',add:'Engadir',edit:'Editar',delete:'Eliminar',export:'Exportar',import:'Importar',confirm:'Confirmar',back:'Volver',close:'Pechar',yes:'Si',no:'Non',filter:'Filtrar',all:'Todos',today:'Hoxe',print:'Imprimir'},
  en:{logout:'Log out',settings:'Settings',lang_ok:'Language saved',search:'Search',noData:'No data',loading:'Loading...',error:'Error',save:'Save',cancel:'Cancel',add:'Add',edit:'Edit',delete:'Delete',export:'Export',import:'Import',confirm:'Confirm',back:'Back',close:'Close',yes:'Yes',no:'No',filter:'Filter',all:'All',today:'Today',print:'Print'},
  fr:{logout:'Déconnexion',settings:'Paramètres',lang_ok:'Langue sauvegardée',search:'Rechercher',noData:'Aucune donnée',loading:'Chargement...',error:'Erreur',save:'Enregistrer',cancel:'Annuler',add:'Ajouter',edit:'Modifier',delete:'Supprimer',export:'Exporter',import:'Importer',confirm:'Confirmer',back:'Retour',close:'Fermer',yes:'Oui',no:'Non',filter:'Filtrer',all:'Tous',today:"Aujourd'hui",print:'Imprimer'},
  de:{logout:'Abmelden',settings:'Einstellungen',lang_ok:'Sprache gespeichert',search:'Suchen',noData:'Keine Daten',loading:'Laden...',error:'Fehler',save:'Speichern',cancel:'Abbrechen',add:'Hinzufügen',edit:'Bearbeiten',delete:'Löschen',export:'Exportieren',import:'Importieren',confirm:'Bestätigen',back:'Zurück',close:'Schließen',yes:'Ja',no:'Nein',filter:'Filtern',all:'Alle',today:'Heute',print:'Drucken'},
  it:{logout:'Esci',settings:'Impostazioni',lang_ok:'Lingua salvata',search:'Cerca',noData:'Nessun dato',loading:'Caricamento...',error:'Errore',save:'Salva',cancel:'Annulla',add:'Aggiungi',edit:'Modifica',delete:'Elimina',export:'Esporta',import:'Importa',confirm:'Conferma',back:'Indietro',close:'Chiudi',yes:'Sì',no:'No',filter:'Filtra',all:'Tutti',today:'Oggi',print:'Stampa'},
  pt:{logout:'Sair',settings:'Configurações',lang_ok:'Idioma salvo',search:'Pesquisar',noData:'Sem dados',loading:'Carregando...',error:'Erro',save:'Salvar',cancel:'Cancelar',add:'Adicionar',edit:'Editar',delete:'Excluir',export:'Exportar',import:'Importar',confirm:'Confirmar',back:'Voltar',close:'Fechar',yes:'Sim',no:'Não',filter:'Filtrar',all:'Todos',today:'Hoje',print:'Imprimir'},
  pl:{logout:'Wyloguj',settings:'Ustawienia',lang_ok:'Język zapisany',search:'Szukaj',noData:'Brak danych',loading:'Ładowanie...',error:'Błąd',save:'Zapisz',cancel:'Anuluj',add:'Dodaj',edit:'Edytuj',delete:'Usuń',export:'Eksportuj',import:'Importuj',confirm:'Potwierdź',back:'Wróć',close:'Zamknij',yes:'Tak',no:'Nie',filter:'Filtruj',all:'Wszystkie',today:'Dziś',print:'Drukuj'},
  ro:{logout:'Deconectare',settings:'Setări',lang_ok:'Limbă salvată',search:'Căutare',noData:'Fără date',loading:'Se încarcă...',error:'Eroare',save:'Salvează',cancel:'Anulează',add:'Adaugă',edit:'Editează',delete:'Șterge',export:'Exportă',import:'Importă',confirm:'Confirmă',back:'Înapoi',close:'Închide',yes:'Da',no:'Nu',filter:'Filtrează',all:'Toate',today:'Azi',print:'Tipărire'},
  nl:{logout:'Uitloggen',settings:'Instellingen',lang_ok:'Taal opgeslagen',search:'Zoeken',noData:'Geen gegevens',loading:'Laden...',error:'Fout',save:'Opslaan',cancel:'Annuleren',add:'Toevoegen',edit:'Bewerken',delete:'Verwijderen',export:'Exporteren',import:'Importeren',confirm:'Bevestigen',back:'Terug',close:'Sluiten',yes:'Ja',no:'Nee',filter:'Filteren',all:'Alle',today:'Vandaag',print:'Afdrukken'},
  hu:{logout:'Kijelentkezés',settings:'Beállítások',lang_ok:'Nyelv mentve',search:'Keresés',noData:'Nincs adat',loading:'Betöltés...',error:'Hiba',save:'Mentés',cancel:'Mégse',add:'Hozzáadás',edit:'Szerkesztés',delete:'Törlés',export:'Exportálás',import:'Importálás',confirm:'Megerősítés',back:'Vissza',close:'Bezárás',yes:'Igen',no:'Nem',filter:'Szűrés',all:'Összes',today:'Ma',print:'Nyomtatás'},
  cs:{logout:'Odhlásit',settings:'Nastavení',lang_ok:'Jazyk uložen',search:'Hledat',noData:'Žádná data',loading:'Načítání...',error:'Chyba',save:'Uložit',cancel:'Zrušit',add:'Přidat',edit:'Upravit',delete:'Smazat',export:'Exportovat',import:'Importovat',confirm:'Potvrdit',back:'Zpět',close:'Zavřít',yes:'Ano',no:'Ne',filter:'Filtrovat',all:'Vše',today:'Dnes',print:'Tisk'},
  hr:{logout:'Odjava',settings:'Postavke',lang_ok:'Jezik spremljen',search:'Traži',noData:'Nema podataka',loading:'Učitavanje...',error:'Greška',save:'Spremi',cancel:'Odustani',add:'Dodaj',edit:'Uredi',delete:'Obriši',export:'Izvezi',import:'Uvezi',confirm:'Potvrdi',back:'Natrag',close:'Zatvori',yes:'Da',no:'Ne',filter:'Filtriraj',all:'Sve',today:'Danas',print:'Ispis'},
  uk:{logout:'Вийти',settings:'Налаштування',lang_ok:'Мову збережено',search:'Пошук',noData:'Немає даних',loading:'Завантаження...',error:'Помилка',save:'Зберегти',cancel:'Скасувати',add:'Додати',edit:'Редагувати',delete:'Видалити',export:'Експорт',import:'Імпорт',confirm:'Підтвердити',back:'Назад',close:'Закрити',yes:'Так',no:'Ні',filter:'Фільтр',all:'Усі',today:'Сьогодні',print:'Друк'},
  ru:{logout:'Выйти',settings:'Настройки',lang_ok:'Язык сохранён',search:'Поиск',noData:'Нет данных',loading:'Загрузка...',error:'Ошибка',save:'Сохранить',cancel:'Отмена',add:'Добавить',edit:'Редактировать',delete:'Удалить',export:'Экспорт',import:'Импорт',confirm:'Подтвердить',back:'Назад',close:'Закрыть',yes:'Да',no:'Нет',filter:'Фильтр',all:'Все',today:'Сегодня',print:'Печать'},
  tr:{logout:'Çıkış',settings:'Ayarlar',lang_ok:'Dil kaydedildi',search:'Ara',noData:'Veri yok',loading:'Yükleniyor...',error:'Hata',save:'Kaydet',cancel:'İptal',add:'Ekle',edit:'Düzenle',delete:'Sil',export:'Dışa aktar',import:'İçe aktar',confirm:'Onayla',back:'Geri',close:'Kapat',yes:'Evet',no:'Hayır',filter:'Filtrele',all:'Tümü',today:'Bugün',print:'Yazdır'},
  ar:{logout:'تسجيل خروج',settings:'إعدادات',lang_ok:'تم حفظ اللغة',search:'بحث',noData:'لا توجد بيانات',loading:'جاري التحميل...',error:'خطأ',save:'حفظ',cancel:'إلغاء',add:'إضافة',edit:'تعديل',delete:'حذف',export:'تصدير',import:'استيراد',confirm:'تأكيد',back:'رجوع',close:'إغلاق',yes:'نعم',no:'لا',filter:'تصفية',all:'الكل',today:'اليوم',print:'طباعة'},
  sv:{logout:'Logga ut',settings:'Inställningar',lang_ok:'Språk sparat',search:'Sök',noData:'Ingen data',loading:'Laddar...',error:'Fel',save:'Spara',cancel:'Avbryt',add:'Lägg till',edit:'Redigera',delete:'Radera',export:'Exportera',import:'Importera',confirm:'Bekräfta',back:'Tillbaka',close:'Stäng',yes:'Ja',no:'Nej',filter:'Filtrera',all:'Alla',today:'Idag',print:'Skriv ut'},
  fi:{logout:'Kirjaudu ulos',settings:'Asetukset',lang_ok:'Kieli tallennettu',search:'Hae',noData:'Ei tietoja',loading:'Ladataan...',error:'Virhe',save:'Tallenna',cancel:'Peruuta',add:'Lisää',edit:'Muokkaa',delete:'Poista',export:'Vie',import:'Tuo',confirm:'Vahvista',back:'Takaisin',close:'Sulje',yes:'Kyllä',no:'Ei',filter:'Suodata',all:'Kaikki',today:'Tänään',print:'Tulosta'},
  el:{logout:'Αποσύνδεση',settings:'Ρυθμίσεις',lang_ok:'Γλώσσα αποθηκεύτηκε',search:'Αναζήτηση',noData:'Χωρίς δεδομένα',loading:'Φόρτωση...',error:'Σφάλμα',save:'Αποθήκευση',cancel:'Ακύρωση',add:'Προσθήκη',edit:'Επεξεργασία',delete:'Διαγραφή',export:'Εξαγωγή',import:'Εισαγωγή',confirm:'Επιβεβαίωση',back:'Πίσω',close:'Κλείσιμο',yes:'Ναι',no:'Όχι',filter:'Φίλτρο',all:'Όλα',today:'Σήμερα',print:'Εκτύπωση'},
  bg:{logout:'Изход',settings:'Настройки',lang_ok:'Езикът е запазен',search:'Търсене',noData:'Няма данни',loading:'Зареждане...',error:'Грешка',save:'Запази',cancel:'Отказ',add:'Добави',edit:'Редактирай',delete:'Изтрий',export:'Експорт',import:'Импорт',confirm:'Потвърди',back:'Назад',close:'Затвори',yes:'Да',no:'Не',filter:'Филтър',all:'Всички',today:'Днес',print:'Печат'},
  sk:{logout:'Odhlásiť',settings:'Nastavenia',lang_ok:'Jazyk uložený',search:'Hľadať',noData:'Žiadne údaje',loading:'Načítava sa...',error:'Chyba',save:'Uložiť',cancel:'Zrušiť',add:'Pridať',edit:'Upraviť',delete:'Vymazať',export:'Exportovať',import:'Importovať',confirm:'Potvrdiť',back:'Späť',close:'Zavrieť',yes:'Áno',no:'Nie',filter:'Filtrovať',all:'Všetko',today:'Dnes',print:'Tlač'},
  sl:{logout:'Odjava',settings:'Nastavitve',lang_ok:'Jezik shranjen',search:'Iskanje',noData:'Ni podatkov',loading:'Nalaganje...',error:'Napaka',save:'Shrani',cancel:'Prekliči',add:'Dodaj',edit:'Uredi',delete:'Izbriši',export:'Izvozi',import:'Uvozi',confirm:'Potrdi',back:'Nazaj',close:'Zapri',yes:'Da',no:'Ne',filter:'Filtriraj',all:'Vse',today:'Danes',print:'Natisni'},
},

// ── TABS ─────────────────────────────────────────────────
tabs: {
  es:{dash:'📊 Dashboard',ingresos:'🔖 Referencia',ingresos2:'🚛 Ingresos',flota:'📦 Embalaje',conductores:'👤 Conductores',agenda:'📅 Agenda',analytics:'📈 Análisis',vehiculos:'📜 Historial',auditoria:'📂 Archivos',recintos:'🏟 Recintos',usuarios:'👥 Usuarios',eventos:'📅 Eventos',papelera:'🗑 Papelera',mensajes:'📢 Mensajes',impresion:'🖨 Impresión',empresas:'🏢 Empresas',migracion:'💾 Migración'},
  ca:{dash:'📊 Tauler',ingresos:'🔖 Referència',ingresos2:'🚛 Ingressos',flota:'📦 Embalatge',conductores:'👤 Conductors',agenda:'📅 Agenda',analytics:'📈 Anàlisi',vehiculos:'📜 Historial',auditoria:'📂 Arxius',recintos:'🏟 Recintes',usuarios:'👥 Usuaris',eventos:'📅 Esdeveniments',papelera:'🗑 Paperera',mensajes:'📢 Missatges',impresion:'🖨 Impressió',empresas:'🏢 Empreses',migracion:'💾 Migració'},
  eu:{dash:'📊 Panela',ingresos:'🔖 Erreferentzia',ingresos2:'🚛 Sarrerak',flota:'📦 Ontziak',conductores:'👤 Gidariak',agenda:'📅 Agenda',analytics:'📈 Analisia',vehiculos:'📜 Historiala',auditoria:'📂 Fitxategiak',recintos:'🏟 Guneak',usuarios:'👥 Erabiltzaileak',eventos:'📅 Ekitaldiak',papelera:'🗑 Zakarrontzia',mensajes:'📢 Mezuak',impresion:'🖨 Inprimatu',empresas:'🏢 Enpresak',migracion:'💾 Migrazioa'},
  gl:{dash:'📊 Panel',ingresos:'🔖 Referencia',ingresos2:'🚛 Ingresos',flota:'📦 Embalaxe',conductores:'👤 Condutores',agenda:'📅 Axenda',analytics:'📈 Análise',vehiculos:'📜 Historial',auditoria:'📂 Arquivos',recintos:'🏟 Recintos',usuarios:'👥 Usuarios',eventos:'📅 Eventos',papelera:'🗑 Papeleira',mensajes:'📢 Mensaxes',impresion:'🖨 Impresión',empresas:'🏢 Empresas',migracion:'💾 Migración'},
  en:{dash:'📊 Dashboard',ingresos:'🔖 Reference',ingresos2:'🚛 Access',flota:'📦 Packaging',conductores:'👤 Drivers',agenda:'📅 Agenda',analytics:'📈 Analytics',vehiculos:'📜 History',auditoria:'📂 Files',recintos:'🏟 Venues',usuarios:'👥 Users',eventos:'📅 Events',papelera:'🗑 Trash',mensajes:'📢 Messages',impresion:'🖨 Print',empresas:'🏢 Companies',migracion:'💾 Migration'},
  fr:{dash:'📊 Tableau',ingresos:'🔖 Référence',ingresos2:'🚛 Accès',flota:'📦 Emballage',conductores:'👤 Chauffeurs',agenda:'📅 Agenda',analytics:'📈 Analytique',vehiculos:'📜 Historique',auditoria:'📂 Fichiers',recintos:'🏟 Lieux',usuarios:'👥 Utilisateurs',eventos:'📅 Événements',papelera:'🗑 Corbeille',mensajes:'📢 Messages',impresion:'🖨 Impression',empresas:'🏢 Entreprises',migracion:'💾 Migration'},
  de:{dash:'📊 Dashboard',ingresos:'🔖 Referenz',ingresos2:'🚛 Zugang',flota:'📦 Verpackung',conductores:'👤 Fahrer',agenda:'📅 Agenda',analytics:'📈 Analytik',vehiculos:'📜 Verlauf',auditoria:'📂 Dateien',recintos:'🏟 Veranstaltungsorte',usuarios:'👥 Benutzer',eventos:'📅 Events',papelera:'🗑 Papierkorb',mensajes:'📢 Nachrichten',impresion:'🖨 Druck',empresas:'🏢 Firmen',migracion:'💾 Migration'},
  it:{dash:'📊 Dashboard',ingresos:'🔖 Riferimento',ingresos2:'🚛 Accessi',flota:'📦 Imballaggio',conductores:'👤 Autisti',agenda:'📅 Agenda',analytics:'📈 Analisi',vehiculos:'📜 Cronologia',auditoria:'📂 File',recintos:'🏟 Sedi',usuarios:'👥 Utenti',eventos:'📅 Eventi',papelera:'🗑 Cestino',mensajes:'📢 Messaggi',impresion:'🖨 Stampa',empresas:'🏢 Aziende',migracion:'💾 Migrazione'},
  pt:{dash:'📊 Painel',ingresos:'🔖 Referência',ingresos2:'🚛 Acessos',flota:'📦 Embalagem',conductores:'👤 Motoristas',agenda:'📅 Agenda',analytics:'📈 Análise',vehiculos:'📜 Histórico',auditoria:'📂 Arquivos',recintos:'🏟 Recintos',usuarios:'👥 Usuários',eventos:'📅 Eventos',papelera:'🗑 Lixeira',mensajes:'📢 Mensagens',impresion:'🖨 Impressão',empresas:'🏢 Empresas',migracion:'💾 Migração'},
  pl:{dash:'📊 Pulpit',ingresos:'🔖 Referencja',ingresos2:'🚛 Wejścia',flota:'📦 Pakowanie',conductores:'👤 Kierowcy',agenda:'📅 Agenda',analytics:'📈 Analityka',vehiculos:'📜 Historia',auditoria:'📂 Pliki',recintos:'🏟 Obiekty',usuarios:'👥 Użytkownicy',eventos:'📅 Wydarzenia',papelera:'🗑 Kosz',mensajes:'📢 Wiadomości',impresion:'🖨 Druk',empresas:'🏢 Firmy',migracion:'💾 Migracja'},
  ro:{dash:'📊 Panou',ingresos:'🔖 Referință',ingresos2:'🚛 Intrări',flota:'📦 Ambalare',conductores:'👤 Șoferi',agenda:'📅 Agendă',analytics:'📈 Analiză',vehiculos:'📜 Istoric',auditoria:'📂 Fișiere',recintos:'🏟 Locații',usuarios:'👥 Utilizatori',eventos:'📅 Evenimente',papelera:'🗑 Coș',mensajes:'📢 Mesaje',impresion:'🖨 Tipărire',empresas:'🏢 Companii',migracion:'💾 Migrare'},
  nl:{dash:'📊 Dashboard',ingresos:'🔖 Referentie',ingresos2:'🚛 Toegang',flota:'📦 Verpakking',conductores:'👤 Chauffeurs',agenda:'📅 Agenda',analytics:'📈 Analyse',vehiculos:'📜 Geschiedenis',auditoria:'📂 Bestanden',recintos:'🏟 Locaties',usuarios:'👥 Gebruikers',eventos:'📅 Evenementen',papelera:'🗑 Prullenbak',mensajes:'📢 Berichten',impresion:'🖨 Afdrukken',empresas:'🏢 Bedrijven',migracion:'💾 Migratie'},
  hu:{dash:'📊 Irányítópult',ingresos:'🔖 Referencia',ingresos2:'🚛 Belépés',flota:'📦 Csomagolás',conductores:'👤 Sofőrök',agenda:'📅 Napirend',analytics:'📈 Elemzés',vehiculos:'📜 Előzmények',auditoria:'📂 Fájlok',recintos:'🏟 Helyszínek',usuarios:'👥 Felhasználók',eventos:'📅 Események',papelera:'🗑 Szemetes',mensajes:'📢 Üzenetek',impresion:'🖨 Nyomtatás',empresas:'🏢 Cégek',migracion:'💾 Migráció'},
  cs:{dash:'📊 Přehled',ingresos:'🔖 Reference',ingresos2:'🚛 Vstupy',flota:'📦 Balení',conductores:'👤 Řidiči',agenda:'📅 Agenda',analytics:'📈 Analýza',vehiculos:'📜 Historie',auditoria:'📂 Soubory',recintos:'🏟 Prostory',usuarios:'👥 Uživatelé',eventos:'📅 Události',papelera:'🗑 Koš',mensajes:'📢 Zprávy',impresion:'🖨 Tisk',empresas:'🏢 Firmy',migracion:'💾 Migrace'},
  hr:{dash:'📊 Nadzorna ploča',ingresos:'🔖 Referenca',ingresos2:'🚛 Pristup',flota:'📦 Pakiranje',conductores:'👤 Vozači',agenda:'📅 Raspored',analytics:'📈 Analitika',vehiculos:'📜 Povijest',auditoria:'📂 Datoteke',recintos:'🏟 Objekti',usuarios:'👥 Korisnici',eventos:'📅 Događaji',papelera:'🗑 Smeće',mensajes:'📢 Poruke',impresion:'🖨 Ispis',empresas:'🏢 Tvrtke',migracion:'💾 Migracija'},
  uk:{dash:'📊 Панель',ingresos:'🔖 Довідка',ingresos2:'🚛 Доступ',flota:'📦 Пакування',conductores:'👤 Водії',agenda:'📅 Розклад',analytics:'📈 Аналітика',vehiculos:'📜 Історія',auditoria:'📂 Файли',recintos:'🏟 Об\'єкти',usuarios:'👥 Користувачі',eventos:'📅 Події',papelera:'🗑 Кошик',mensajes:'📢 Повідомлення',impresion:'🖨 Друк',empresas:'🏢 Компанії',migracion:'💾 Міграція'},
  ru:{dash:'📊 Панель',ingresos:'🔖 Справка',ingresos2:'🚛 Доступ',flota:'📦 Упаковка',conductores:'👤 Водители',agenda:'📅 Расписание',analytics:'📈 Аналитика',vehiculos:'📜 История',auditoria:'📂 Файлы',recintos:'🏟 Объекты',usuarios:'👥 Пользователи',eventos:'📅 События',papelera:'🗑 Корзина',mensajes:'📢 Сообщения',impresion:'🖨 Печать',empresas:'🏢 Компании',migracion:'💾 Миграция'},
  tr:{dash:'📊 Panel',ingresos:'🔖 Referans',ingresos2:'🚛 Giriş',flota:'📦 Ambalaj',conductores:'👤 Sürücüler',agenda:'📅 Ajanda',analytics:'📈 Analiz',vehiculos:'📜 Geçmiş',auditoria:'📂 Dosyalar',recintos:'🏟 Mekanlar',usuarios:'👥 Kullanıcılar',eventos:'📅 Etkinlikler',papelera:'🗑 Çöp',mensajes:'📢 Mesajlar',impresion:'🖨 Yazdır',empresas:'🏢 Şirketler',migracion:'💾 Göç'},
  ar:{dash:'📊 لوحة',ingresos:'🔖 مرجع',ingresos2:'🚛 دخول',flota:'📦 تغليف',conductores:'👤 سائقون',agenda:'📅 جدول',analytics:'📈 تحليل',vehiculos:'📜 سجل',auditoria:'📂 ملفات',recintos:'🏟 مواقع',usuarios:'👥 مستخدمون',eventos:'📅 فعاليات',papelera:'🗑 سلة',mensajes:'📢 رسائل',impresion:'🖨 طباعة',empresas:'🏢 شركات',migracion:'💾 ترحيل'},
  sv:{dash:'📊 Översikt',ingresos:'🔖 Referens',ingresos2:'🚛 Tillträde',flota:'📦 Förpackning',conductores:'👤 Förare',agenda:'📅 Agenda',analytics:'📈 Analys',vehiculos:'📜 Historik',auditoria:'📂 Filer',recintos:'🏟 Platser',usuarios:'👥 Användare',eventos:'📅 Evenemang',papelera:'🗑 Papperskorg',mensajes:'📢 Meddelanden',impresion:'🖨 Skriv ut',empresas:'🏢 Företag',migracion:'💾 Migrering'},
  fi:{dash:'📊 Hallintapaneeli',ingresos:'🔖 Viite',ingresos2:'🚛 Pääsy',flota:'📦 Pakkaus',conductores:'👤 Kuljettajat',agenda:'📅 Kalenteri',analytics:'📈 Analytiikka',vehiculos:'📜 Historia',auditoria:'📂 Tiedostot',recintos:'🏟 Paikat',usuarios:'👥 Käyttäjät',eventos:'📅 Tapahtumat',papelera:'🗑 Roskakori',mensajes:'📢 Viestit',impresion:'🖨 Tulosta',empresas:'🏢 Yritykset',migracion:'💾 Migraatio'},
  el:{dash:'📊 Πίνακας',ingresos:'🔖 Αναφορά',ingresos2:'🚛 Πρόσβαση',flota:'📦 Συσκευασία',conductores:'👤 Οδηγοί',agenda:'📅 Ατζέντα',analytics:'📈 Ανάλυση',vehiculos:'📜 Ιστορικό',auditoria:'📂 Αρχεία',recintos:'🏟 Χώροι',usuarios:'👥 Χρήστες',eventos:'📅 Εκδηλώσεις',papelera:'🗑 Κάδος',mensajes:'📢 Μηνύματα',impresion:'🖨 Εκτύπωση',empresas:'🏢 Εταιρείες',migracion:'💾 Μετεγκατάσταση'},
  bg:{dash:'📊 Табло',ingresos:'🔖 Справка',ingresos2:'🚛 Достъп',flota:'📦 Опаковане',conductores:'👤 Шофьори',agenda:'📅 График',analytics:'📈 Анализ',vehiculos:'📜 История',auditoria:'📂 Файлове',recintos:'🏟 Обекти',usuarios:'👥 Потребители',eventos:'📅 Събития',papelera:'🗑 Кошче',mensajes:'📢 Съобщения',impresion:'🖨 Печат',empresas:'🏢 Фирми',migracion:'💾 Миграция'},
  sk:{dash:'📊 Prehľad',ingresos:'🔖 Referencia',ingresos2:'🚛 Vstupy',flota:'📦 Balenie',conductores:'👤 Vodiči',agenda:'📅 Agenda',analytics:'📈 Analýza',vehiculos:'📜 História',auditoria:'📂 Súbory',recintos:'🏟 Areály',usuarios:'👥 Používatelia',eventos:'📅 Udalosti',papelera:'🗑 Kôš',mensajes:'📢 Správy',impresion:'🖨 Tlač',empresas:'🏢 Firmy',migracion:'💾 Migrácia'},
  sl:{dash:'📊 Nadzorna plošča',ingresos:'🔖 Referenca',ingresos2:'🚛 Dostop',flota:'📦 Pakiranje',conductores:'👤 Vozniki',agenda:'📅 Urnik',analytics:'📈 Analiza',vehiculos:'📜 Zgodovina',auditoria:'📂 Datoteke',recintos:'🏟 Lokacije',usuarios:'👥 Uporabniki',eventos:'📅 Dogodki',papelera:'🗑 Koš',mensajes:'📢 Sporočila',impresion:'🖨 Natisni',empresas:'🏢 Podjetja',migracion:'💾 Migracija'},
},

// ── AUTH ─────────────────────────────────────────────────
auth: {
  es:{title:'Iniciar sesión',email:'Email',password:'Contraseña',login:'Acceder',register:'Registrar empresa',forgot:'¿Olvidaste tu contraseña?',error_cred:'Credenciales incorrectas',error_net:'Error de conexión',welcome:'Bienvenido'},
  ca:{title:'Iniciar sessió',email:'Correu',password:'Contrasenya',login:'Accedir',register:'Registrar empresa',forgot:'Has oblidat la contrasenya?',error_cred:'Credencials incorrectes',error_net:'Error de connexió',welcome:'Benvingut'},
  eu:{title:'Saioa hasi',email:'Emaila',password:'Pasahitza',login:'Sartu',register:'Enpresa erregistratu',forgot:'Pasahitza ahaztu duzu?',error_cred:'Kredentzial okerrak',error_net:'Konexio errorea',welcome:'Ongi etorri'},
  gl:{title:'Iniciar sesión',email:'Correo',password:'Contrasinal',login:'Acceder',register:'Rexistrar empresa',forgot:'Esqueciches o contrasinal?',error_cred:'Credenciais incorrectas',error_net:'Erro de conexión',welcome:'Benvido'},
  en:{title:'Log in',email:'Email',password:'Password',login:'Sign in',register:'Register company',forgot:'Forgot your password?',error_cred:'Invalid credentials',error_net:'Connection error',welcome:'Welcome'},
  fr:{title:'Connexion',email:'Email',password:'Mot de passe',login:'Se connecter',register:'Enregistrer entreprise',forgot:'Mot de passe oublié ?',error_cred:'Identifiants incorrects',error_net:'Erreur de connexion',welcome:'Bienvenue'},
  de:{title:'Anmelden',email:'Email',password:'Passwort',login:'Einloggen',register:'Firma registrieren',forgot:'Passwort vergessen?',error_cred:'Ungültige Anmeldedaten',error_net:'Verbindungsfehler',welcome:'Willkommen'},
  it:{title:'Accedi',email:'Email',password:'Password',login:'Entra',register:'Registra azienda',forgot:'Password dimenticata?',error_cred:'Credenziali errate',error_net:'Errore di connessione',welcome:'Benvenuto'},
  pt:{title:'Entrar',email:'Email',password:'Senha',login:'Acessar',register:'Registrar empresa',forgot:'Esqueceu a senha?',error_cred:'Credenciais inválidas',error_net:'Erro de conexão',welcome:'Bem-vindo'},
  pl:{title:'Zaloguj się',email:'Email',password:'Hasło',login:'Zaloguj',register:'Zarejestruj firmę',forgot:'Zapomniałeś hasła?',error_cred:'Nieprawidłowe dane',error_net:'Błąd połączenia',welcome:'Witamy'},
  ro:{title:'Conectare',email:'Email',password:'Parolă',login:'Accesează',register:'Înregistrează companie',forgot:'Ai uitat parola?',error_cred:'Date incorecte',error_net:'Eroare de conexiune',welcome:'Bine ai venit'},
  nl:{title:'Inloggen',email:'Email',password:'Wachtwoord',login:'Inloggen',register:'Bedrijf registreren',forgot:'Wachtwoord vergeten?',error_cred:'Ongeldige gegevens',error_net:'Verbindingsfout',welcome:'Welkom'},
  hu:{title:'Bejelentkezés',email:'Email',password:'Jelszó',login:'Belépés',register:'Cég regisztráció',forgot:'Elfelejtett jelszó?',error_cred:'Hibás adatok',error_net:'Kapcsolódási hiba',welcome:'Üdvözöljük'},
  cs:{title:'Přihlášení',email:'Email',password:'Heslo',login:'Přihlásit',register:'Registrovat firmu',forgot:'Zapomněli jste heslo?',error_cred:'Nesprávné údaje',error_net:'Chyba připojení',welcome:'Vítejte'},
  hr:{title:'Prijava',email:'Email',password:'Lozinka',login:'Prijavi se',register:'Registriraj tvrtku',forgot:'Zaboravili ste lozinku?',error_cred:'Neispravni podaci',error_net:'Greška veze',welcome:'Dobrodošli'},
  uk:{title:'Увійти',email:'Електронна пошта',password:'Пароль',login:'Увійти',register:'Зареєструвати компанію',forgot:'Забули пароль?',error_cred:'Невірні дані',error_net:'Помилка з\'єднання',welcome:'Ласкаво просимо'},
  ru:{title:'Войти',email:'Электронная почта',password:'Пароль',login:'Войти',register:'Зарегистрировать компанию',forgot:'Забыли пароль?',error_cred:'Неверные данные',error_net:'Ошибка соединения',welcome:'Добро пожаловать'},
  tr:{title:'Giriş yap',email:'E-posta',password:'Şifre',login:'Giriş',register:'Şirket kaydı',forgot:'Şifrenizi mi unuttunuz?',error_cred:'Geçersiz bilgiler',error_net:'Bağlantı hatası',welcome:'Hoş geldiniz'},
  ar:{title:'تسجيل الدخول',email:'البريد الإلكتروني',password:'كلمة المرور',login:'دخول',register:'تسجيل شركة',forgot:'نسيت كلمة المرور؟',error_cred:'بيانات غير صحيحة',error_net:'خطأ في الاتصال',welcome:'مرحباً'},
  sv:{title:'Logga in',email:'E-post',password:'Lösenord',login:'Logga in',register:'Registrera företag',forgot:'Glömt lösenord?',error_cred:'Ogiltiga uppgifter',error_net:'Anslutningsfel',welcome:'Välkommen'},
  fi:{title:'Kirjaudu',email:'Sähköposti',password:'Salasana',login:'Kirjaudu',register:'Rekisteröi yritys',forgot:'Unohditko salasanan?',error_cred:'Virheelliset tiedot',error_net:'Yhteysvirhe',welcome:'Tervetuloa'},
  el:{title:'Σύνδεση',email:'Email',password:'Κωδικός',login:'Είσοδος',register:'Εγγραφή εταιρείας',forgot:'Ξεχάσατε τον κωδικό;',error_cred:'Λάθος στοιχεία',error_net:'Σφάλμα σύνδεσης',welcome:'Καλώς ήρθατε'},
  bg:{title:'Вход',email:'Имейл',password:'Парола',login:'Влез',register:'Регистрация на фирма',forgot:'Забравена парола?',error_cred:'Грешни данни',error_net:'Грешка при свързване',welcome:'Добре дошли'},
  sk:{title:'Prihlásenie',email:'Email',password:'Heslo',login:'Prihlásiť',register:'Registrovať firmu',forgot:'Zabudli ste heslo?',error_cred:'Nesprávne údaje',error_net:'Chyba pripojenia',welcome:'Vitajte'},
  sl:{title:'Prijava',email:'E-pošta',password:'Geslo',login:'Prijavi se',register:'Registriraj podjetje',forgot:'Pozabljeno geslo?',error_cred:'Napačni podatki',error_net:'Napaka povezave',welcome:'Dobrodošli'},
},

// ── DASH ─────────────────────────────────────────────────
dash: {
  es:{title:'Dashboard',enRecinto:'En recinto',referencias:'Referencias',ingresosHoy:'Ingresos hoy',agendaHoy:'Agenda hoy',mensajes:'Mensajes',ultimos7:'Últimos 7 días',hallsActivos:'Halls activos',ultimasEntradas:'Últimas entradas'},
  ca:{title:'Tauler',enRecinto:'Al recinte',referencias:'Referències',ingresosHoy:'Ingressos avui',agendaHoy:'Agenda avui',mensajes:'Missatges',ultimos7:'Últims 7 dies',hallsActivos:'Halls actius',ultimasEntradas:'Últimes entrades'},
  eu:{title:'Panela',enRecinto:'Gunean',referencias:'Erreferentziak',ingresosHoy:'Gaur sarrerak',agendaHoy:'Gaur agenda',mensajes:'Mezuak',ultimos7:'Azken 7 egunak',hallsActivos:'Hall aktiboak',ultimasEntradas:'Azken sarrerak'},
  gl:{title:'Panel',enRecinto:'No recinto',referencias:'Referencias',ingresosHoy:'Ingresos hoxe',agendaHoy:'Axenda hoxe',mensajes:'Mensaxes',ultimos7:'Últimos 7 días',hallsActivos:'Halls activos',ultimasEntradas:'Últimas entradas'},
  en:{title:'Dashboard',enRecinto:'On premises',referencias:'References',ingresosHoy:'Access today',agendaHoy:'Agenda today',mensajes:'Messages',ultimos7:'Last 7 days',hallsActivos:'Active halls',ultimasEntradas:'Latest entries'},
  fr:{title:'Tableau de bord',enRecinto:"Dans l'enceinte",referencias:'Références',ingresosHoy:"Accès aujourd'hui",agendaHoy:"Agenda aujourd'hui",mensajes:'Messages',ultimos7:'7 derniers jours',hallsActivos:'Halls actifs',ultimasEntradas:'Dernières entrées'},
  de:{title:'Dashboard',enRecinto:'Im Gelände',referencias:'Referenzen',ingresosHoy:'Zugang heute',agendaHoy:'Agenda heute',mensajes:'Nachrichten',ultimos7:'Letzte 7 Tage',hallsActivos:'Aktive Hallen',ultimasEntradas:'Letzte Einträge'},
  it:{title:'Dashboard',enRecinto:'In sede',referencias:'Riferimenti',ingresosHoy:'Accessi oggi',agendaHoy:'Agenda oggi',mensajes:'Messaggi',ultimos7:'Ultimi 7 giorni',hallsActivos:'Hall attivi',ultimasEntradas:'Ultimi ingressi'},
  pt:{title:'Painel',enRecinto:'No recinto',referencias:'Referências',ingresosHoy:'Acessos hoje',agendaHoy:'Agenda hoje',mensajes:'Mensagens',ultimos7:'Últimos 7 dias',hallsActivos:'Halls ativos',ultimasEntradas:'Últimas entradas'},
  pl:{title:'Pulpit',enRecinto:'Na terenie',referencias:'Referencje',ingresosHoy:'Wejścia dziś',agendaHoy:'Agenda dziś',mensajes:'Wiadomości',ultimos7:'Ostatnie 7 dni',hallsActivos:'Aktywne hale',ultimasEntradas:'Ostatnie wpisy'},
  ro:{title:'Panou',enRecinto:'În incintă',referencias:'Referințe',ingresosHoy:'Intrări azi',agendaHoy:'Agendă azi',mensajes:'Mesaje',ultimos7:'Ultimele 7 zile',hallsActivos:'Hale active',ultimasEntradas:'Ultimele intrări'},
  nl:{title:'Dashboard',enRecinto:'Op terrein',referencias:'Referenties',ingresosHoy:'Toegang vandaag',agendaHoy:'Agenda vandaag',mensajes:'Berichten',ultimos7:'Laatste 7 dagen',hallsActivos:'Actieve hallen',ultimasEntradas:'Laatste invoer'},
  hu:{title:'Irányítópult',enRecinto:'A területen',referencias:'Referenciák',ingresosHoy:'Mai belépések',agendaHoy:'Mai napirend',mensajes:'Üzenetek',ultimos7:'Utolsó 7 nap',hallsActivos:'Aktív csarnokok',ultimasEntradas:'Utolsó bejegyzések'},
  cs:{title:'Přehled',enRecinto:'V areálu',referencias:'Reference',ingresosHoy:'Vstupy dnes',agendaHoy:'Agenda dnes',mensajes:'Zprávy',ultimos7:'Posledních 7 dní',hallsActivos:'Aktivní haly',ultimasEntradas:'Poslední záznamy'},
  hr:{title:'Nadzorna ploča',enRecinto:'U prostoru',referencias:'Reference',ingresosHoy:'Pristup danas',agendaHoy:'Raspored danas',mensajes:'Poruke',ultimos7:'Zadnjih 7 dana',hallsActivos:'Aktivne dvorane',ultimasEntradas:'Zadnji unosi'},
  uk:{title:'Панель',enRecinto:'На території',referencias:'Довідки',ingresosHoy:'Доступ сьогодні',agendaHoy:'Розклад сьогодні',mensajes:'Повідомлення',ultimos7:'Останні 7 днів',hallsActivos:'Активні зали',ultimasEntradas:'Останні записи'},
  ru:{title:'Панель',enRecinto:'На территории',referencias:'Справки',ingresosHoy:'Доступ сегодня',agendaHoy:'Расписание сегодня',mensajes:'Сообщения',ultimos7:'Последние 7 дней',hallsActivos:'Активные залы',ultimasEntradas:'Последние записи'},
  tr:{title:'Panel',enRecinto:'Alanda',referencias:'Referanslar',ingresosHoy:'Bugün giriş',agendaHoy:'Bugün ajanda',mensajes:'Mesajlar',ultimos7:'Son 7 gün',hallsActivos:'Aktif salonlar',ultimasEntradas:'Son girişler'},
  ar:{title:'لوحة',enRecinto:'في الموقع',referencias:'مراجع',ingresosHoy:'دخول اليوم',agendaHoy:'جدول اليوم',mensajes:'رسائل',ultimos7:'آخر 7 أيام',hallsActivos:'قاعات نشطة',ultimasEntradas:'آخر الإدخالات'},
  sv:{title:'Översikt',enRecinto:'På plats',referencias:'Referenser',ingresosHoy:'Tillträde idag',agendaHoy:'Agenda idag',mensajes:'Meddelanden',ultimos7:'Senaste 7 dagar',hallsActivos:'Aktiva hallar',ultimasEntradas:'Senaste poster'},
  fi:{title:'Hallintapaneeli',enRecinto:'Alueella',referencias:'Viitteet',ingresosHoy:'Pääsy tänään',agendaHoy:'Kalenteri tänään',mensajes:'Viestit',ultimos7:'Viimeiset 7 päivää',hallsActivos:'Aktiiviset hallit',ultimasEntradas:'Viimeisimmät merkinnät'},
  el:{title:'Πίνακας',enRecinto:'Στον χώρο',referencias:'Αναφορές',ingresosHoy:'Πρόσβαση σήμερα',agendaHoy:'Ατζέντα σήμερα',mensajes:'Μηνύματα',ultimos7:'Τελευταίες 7 μέρες',hallsActivos:'Ενεργές αίθουσες',ultimasEntradas:'Τελευταίες καταχωρήσεις'},
  bg:{title:'Табло',enRecinto:'В района',referencias:'Справки',ingresosHoy:'Достъп днес',agendaHoy:'График днес',mensajes:'Съобщения',ultimos7:'Последни 7 дни',hallsActivos:'Активни зали',ultimasEntradas:'Последни записи'},
  sk:{title:'Prehľad',enRecinto:'V areáli',referencias:'Referencie',ingresosHoy:'Vstupy dnes',agendaHoy:'Agenda dnes',mensajes:'Správy',ultimos7:'Posledných 7 dní',hallsActivos:'Aktívne haly',ultimasEntradas:'Posledné záznamy'},
  sl:{title:'Nadzorna plošča',enRecinto:'Na lokaciji',referencias:'Reference',ingresosHoy:'Dostop danes',agendaHoy:'Urnik danes',mensajes:'Sporočila',ultimos7:'Zadnjih 7 dni',hallsActivos:'Aktivne dvorane',ultimasEntradas:'Zadnji vnosi'},
},

// ── INGRESOS ─────────────────────────────────────────────
ingresos: {
  es:{title:'Referencia',matricula:'Matrícula Tractora',remolque:'Remolque',empresa:'Empresa',montador:'Montador',expositor:'Expositor',hall:'Hall',stand:'Stand',puerta:'Puerta Hall',nombre:'Nombre',apellido:'Apellido',pasaporte:'Pasaporte / DNI',telefono:'Teléfono',email:'Email',horaIngreso:'Hora Ingreso',llamador:'Nº Llamador',referencia:'Referencia',obs:'Observaciones',lista:'Lista',especial:'Especial',historial:'Historial',campos:'Campos',estado:'Estado',tipoVeh:'Tipo Vehículo',descarga:'Descarga'},
  ca:{title:'Referència',matricula:'Matrícula Tractora',remolque:'Remolc',empresa:'Empresa',montador:'Muntador',expositor:'Expositor',hall:'Hall',stand:'Stand',puerta:'Porta Hall',nombre:'Nom',apellido:'Cognom',pasaporte:'Passaport / DNI',telefono:'Telèfon',email:'Correu',horaIngreso:'Hora Ingrés',llamador:'Nº Trucador',referencia:'Referència',obs:'Observacions',lista:'Llista',especial:'Especial',historial:'Historial',campos:'Camps',estado:'Estat',tipoVeh:'Tipus Vehicle',descarga:'Descàrrega'},
  eu:{title:'Erreferentzia',matricula:'Matrikula',remolque:'Atoika',empresa:'Enpresa',montador:'Muntatzailea',expositor:'Erakuslea',hall:'Aretoa',stand:'Standa',puerta:'Ate',nombre:'Izena',apellido:'Abizena',pasaporte:'Pasaportea',telefono:'Telefonoa',email:'Emaila',horaIngreso:'Sarrera ordua',llamador:'Deitzaile zk.',referencia:'Erreferentzia',obs:'Oharrak',lista:'Zerrenda',especial:'Berezia',historial:'Historiala',campos:'Eremuak',estado:'Egoera',tipoVeh:'Ibilgailu mota',descarga:'Deskarga'},
  gl:{title:'Referencia',matricula:'Matrícula Tractora',remolque:'Remolque',empresa:'Empresa',montador:'Montador',expositor:'Expositor',hall:'Hall',stand:'Stand',puerta:'Porta Hall',nombre:'Nome',apellido:'Apelido',pasaporte:'Pasaporte / DNI',telefono:'Teléfono',email:'Correo',horaIngreso:'Hora Ingreso',llamador:'Nº Chamador',referencia:'Referencia',obs:'Observacións',lista:'Lista',especial:'Especial',historial:'Historial',campos:'Campos',estado:'Estado',tipoVeh:'Tipo Vehículo',descarga:'Descarga'},
  en:{title:'Reference',matricula:'Tractor Plate',remolque:'Trailer',empresa:'Company',montador:'Installer',expositor:'Exhibitor',hall:'Hall',stand:'Stand',puerta:'Hall Gate',nombre:'First Name',apellido:'Last Name',pasaporte:'Passport / ID',telefono:'Phone',email:'Email',horaIngreso:'Entry Time',llamador:'Caller No.',referencia:'Reference',obs:'Observations',lista:'List',especial:'Special',historial:'History',campos:'Fields',estado:'Status',tipoVeh:'Vehicle Type',descarga:'Unloading'},
  fr:{title:'Référence',matricula:'Immatriculation',remolque:'Remorque',empresa:'Société',montador:'Installateur',expositor:'Exposant',hall:'Hall',stand:'Stand',puerta:'Porte Hall',nombre:'Prénom',apellido:'Nom',pasaporte:'Passeport',telefono:'Téléphone',email:'Email',horaIngreso:'Entrée',llamador:'N° Appelant',referencia:'Référence',obs:'Observations',lista:'Liste',especial:'Spécial',historial:'Historique',campos:'Champs',estado:'Statut',tipoVeh:'Type Véhicule',descarga:'Déchargement'},
  de:{title:'Referenz',matricula:'Kennzeichen',remolque:'Anhänger',empresa:'Firma',montador:'Monteur',expositor:'Aussteller',hall:'Halle',stand:'Stand',puerta:'Hallentor',nombre:'Vorname',apellido:'Nachname',pasaporte:'Reisepass',telefono:'Telefon',email:'Email',horaIngreso:'Einfahrt',llamador:'Anrufer Nr.',referencia:'Referenz',obs:'Bemerkungen',lista:'Liste',especial:'Spezial',historial:'Verlauf',campos:'Felder',estado:'Status',tipoVeh:'Fahrzeugtyp',descarga:'Entladung'},
  it:{title:'Riferimento',matricula:'Targa',remolque:'Rimorchio',empresa:'Azienda',montador:'Montatore',expositor:'Espositore',hall:'Padiglione',stand:'Stand',puerta:'Porta Hall',nombre:'Nome',apellido:'Cognome',pasaporte:'Passaporto',telefono:'Telefono',email:'Email',horaIngreso:'Ingresso',llamador:'N° Chiamante',referencia:'Riferimento',obs:'Note',lista:'Lista',especial:'Speciale',historial:'Cronologia',campos:'Campi',estado:'Stato',tipoVeh:'Tipo Veicolo',descarga:'Scarico'},
  pt:{title:'Referência',matricula:'Matrícula',remolque:'Reboque',empresa:'Empresa',montador:'Montador',expositor:'Expositor',hall:'Hall',stand:'Stand',puerta:'Porta Hall',nombre:'Nome',apellido:'Apelido',pasaporte:'Passaporte',telefono:'Telefone',email:'Email',horaIngreso:'Entrada',llamador:'N° Chamador',referencia:'Referência',obs:'Observações',lista:'Lista',especial:'Especial',historial:'Histórico',campos:'Campos',estado:'Estado',tipoVeh:'Tipo Veículo',descarga:'Descarga'},
  pl:{title:'Referencja',matricula:'Rejestracja',remolque:'Przyczepa',empresa:'Firma',montador:'Monter',expositor:'Wystawca',hall:'Hala',stand:'Stoisko',puerta:'Brama',nombre:'Imię',apellido:'Nazwisko',pasaporte:'Paszport',telefono:'Telefon',email:'Email',horaIngreso:'Wejście',llamador:'Nr Wywołania',referencia:'Referencja',obs:'Uwagi',lista:'Lista',especial:'Specjalne',historial:'Historia',campos:'Pola',estado:'Status',tipoVeh:'Typ Pojazdu',descarga:'Rozładunek'},
  ro:{title:'Referință',matricula:'Înmatriculare',remolque:'Remorcă',empresa:'Companie',montador:'Montator',expositor:'Expozant',hall:'Hală',stand:'Stand',puerta:'Poartă',nombre:'Prenume',apellido:'Nume',pasaporte:'Pașaport',telefono:'Telefon',email:'Email',horaIngreso:'Intrare',llamador:'Nr. Apelant',referencia:'Referință',obs:'Observații',lista:'Listă',especial:'Special',historial:'Istoric',campos:'Câmpuri',estado:'Stare',tipoVeh:'Tip Vehicul',descarga:'Descărcare'},
  nl:{title:'Referentie',matricula:'Kenteken',remolque:'Aanhanger',empresa:'Bedrijf',montador:'Monteur',expositor:'Exposant',hall:'Hal',stand:'Stand',puerta:'Poort',nombre:'Voornaam',apellido:'Achternaam',pasaporte:'Paspoort',telefono:'Telefoon',email:'Email',horaIngreso:'Ingang',llamador:'Beller Nr.',referencia:'Referentie',obs:'Opmerkingen',lista:'Lijst',especial:'Speciaal',historial:'Geschiedenis',campos:'Velden',estado:'Status',tipoVeh:'Voertuigtype',descarga:'Lossen'},
  hu:{title:'Referencia',matricula:'Rendszám',remolque:'Pótkocsi',empresa:'Cég',montador:'Szerelő',expositor:'Kiállító',hall:'Csarnok',stand:'Stand',puerta:'Kapu',nombre:'Keresztnév',apellido:'Vezetéknév',pasaporte:'Útlevél',telefono:'Telefon',email:'Email',horaIngreso:'Belépés',llamador:'Hívó száma',referencia:'Referencia',obs:'Megjegyzések',lista:'Lista',especial:'Speciális',historial:'Előzmények',campos:'Mezők',estado:'Állapot',tipoVeh:'Jármű Típus',descarga:'Kirakodás'},
  cs:{title:'Reference',matricula:'SPZ',remolque:'Přívěs',empresa:'Firma',montador:'Montér',expositor:'Vystavovatel',hall:'Hala',stand:'Stánek',puerta:'Brána',nombre:'Jméno',apellido:'Příjmení',pasaporte:'Pas/OP',telefono:'Telefon',email:'Email',horaIngreso:'Vstup',llamador:'Číslo volajícího',referencia:'Reference',obs:'Poznámky',lista:'Seznam',especial:'Speciální',historial:'Historie',campos:'Pole',estado:'Stav',tipoVeh:'Typ vozidla',descarga:'Vykládka'},
  hr:{title:'Referenca',matricula:'Registracija',remolque:'Prikolica',empresa:'Tvrtka',montador:'Monter',expositor:'Izlagač',hall:'Dvorana',stand:'Štand',puerta:'Vrata',nombre:'Ime',apellido:'Prezime',pasaporte:'Putovnica',telefono:'Telefon',email:'Email',horaIngreso:'Ulaz',llamador:'Broj pozivatelja',referencia:'Referenca',obs:'Napomene',lista:'Popis',especial:'Posebno',historial:'Povijest',campos:'Polja',estado:'Status',tipoVeh:'Vrsta Vozila',descarga:'Istovar'},
  uk:{title:'Довідка',matricula:'Номерний знак',remolque:'Причіп',empresa:'Компанія',montador:'Монтажник',expositor:'Експонент',hall:'Зал',stand:'Стенд',puerta:'Ворота',nombre:'Ім\'я',apellido:'Прізвище',pasaporte:'Паспорт',telefono:'Телефон',email:'Email',horaIngreso:'Вхід',llamador:'№ Виклику',referencia:'Довідка',obs:'Примітки',lista:'Список',especial:'Спеціальне',historial:'Історія',campos:'Поля',estado:'Статус',tipoVeh:'Тип ТЗ',descarga:'Розвантаження'},
  ru:{title:'Справка',matricula:'Номер',remolque:'Прицеп',empresa:'Компания',montador:'Монтажник',expositor:'Экспонент',hall:'Зал',stand:'Стенд',puerta:'Ворота',nombre:'Имя',apellido:'Фамилия',pasaporte:'Паспорт',telefono:'Телефон',email:'Email',horaIngreso:'Вход',llamador:'№ Вызова',referencia:'Справка',obs:'Примечания',lista:'Список',especial:'Специальное',historial:'История',campos:'Поля',estado:'Статус',tipoVeh:'Тип ТС',descarga:'Разгрузка'},
  tr:{title:'Referans',matricula:'Plaka',remolque:'Römork',empresa:'Şirket',montador:'Montajcı',expositor:'Katılımcı',hall:'Salon',stand:'Stand',puerta:'Kapı',nombre:'Ad',apellido:'Soyad',pasaporte:'Pasaport',telefono:'Telefon',email:'E-posta',horaIngreso:'Giriş',llamador:'Arayan No',referencia:'Referans',obs:'Notlar',lista:'Liste',especial:'Özel',historial:'Geçmiş',campos:'Alanlar',estado:'Durum',tipoVeh:'Araç Tipi',descarga:'Boşaltma'},
  ar:{title:'مرجع',matricula:'لوحة',remolque:'مقطورة',empresa:'شركة',montador:'مُركِّب',expositor:'عارض',hall:'قاعة',stand:'جناح',puerta:'بوابة',nombre:'الاسم',apellido:'اللقب',pasaporte:'جواز سفر',telefono:'هاتف',email:'بريد',horaIngreso:'دخول',llamador:'رقم المتصل',referencia:'مرجع',obs:'ملاحظات',lista:'قائمة',especial:'خاص',historial:'سجل',campos:'حقول',estado:'حالة',tipoVeh:'نوع المركبة',descarga:'تفريغ'},
  sv:{title:'Referens',matricula:'Registreringsnummer',remolque:'Släpvagn',empresa:'Företag',montador:'Montör',expositor:'Utställare',hall:'Hall',stand:'Monter',puerta:'Port',nombre:'Förnamn',apellido:'Efternamn',pasaporte:'Pass',telefono:'Telefon',email:'E-post',horaIngreso:'Ankomst',llamador:'Uppringare Nr',referencia:'Referens',obs:'Anteckningar',lista:'Lista',especial:'Special',historial:'Historik',campos:'Fält',estado:'Status',tipoVeh:'Fordonstyp',descarga:'Lossning'},
  fi:{title:'Viite',matricula:'Rekisterinumero',remolque:'Perävaunu',empresa:'Yritys',montador:'Asentaja',expositor:'Näytteilleasettaja',hall:'Halli',stand:'Osasto',puerta:'Portti',nombre:'Etunimi',apellido:'Sukunimi',pasaporte:'Passi',telefono:'Puhelin',email:'Sähköposti',horaIngreso:'Saapuminen',llamador:'Soittajan nro',referencia:'Viite',obs:'Huomiot',lista:'Lista',especial:'Erikois',historial:'Historia',campos:'Kentät',estado:'Tila',tipoVeh:'Ajoneuvotyyppi',descarga:'Purku'},
  el:{title:'Αναφορά',matricula:'Πινακίδα',remolque:'Ρυμουλκούμενο',empresa:'Εταιρεία',montador:'Τεχνικός',expositor:'Εκθέτης',hall:'Αίθουσα',stand:'Περίπτερο',puerta:'Πύλη',nombre:'Όνομα',apellido:'Επώνυμο',pasaporte:'Διαβατήριο',telefono:'Τηλέφωνο',email:'Email',horaIngreso:'Είσοδος',llamador:'Αρ. Καλούντος',referencia:'Αναφορά',obs:'Παρατηρήσεις',lista:'Λίστα',especial:'Ειδικό',historial:'Ιστορικό',campos:'Πεδία',estado:'Κατάσταση',tipoVeh:'Τύπος Οχήματος',descarga:'Εκφόρτωση'},
  bg:{title:'Справка',matricula:'Регистрация',remolque:'Ремарке',empresa:'Фирма',montador:'Монтьор',expositor:'Изложител',hall:'Зала',stand:'Щанд',puerta:'Врата',nombre:'Име',apellido:'Фамилия',pasaporte:'Паспорт',telefono:'Телефон',email:'Имейл',horaIngreso:'Вход',llamador:'№ Обаждане',referencia:'Справка',obs:'Бележки',lista:'Списък',especial:'Специално',historial:'История',campos:'Полета',estado:'Статус',tipoVeh:'Тип МПС',descarga:'Разтоварване'},
  sk:{title:'Referencia',matricula:'ŠPZ',remolque:'Prívěs',empresa:'Firma',montador:'Montér',expositor:'Vystavovateľ',hall:'Hala',stand:'Stánok',puerta:'Brána',nombre:'Meno',apellido:'Priezvisko',pasaporte:'Pas/OP',telefono:'Telefón',email:'Email',horaIngreso:'Vstup',llamador:'Číslo Volajúceho',referencia:'Referencia',obs:'Poznámky',lista:'Zoznam',especial:'Špeciálne',historial:'História',campos:'Polia',estado:'Stav',tipoVeh:'Typ vozidla',descarga:'Vykládka'},
  sl:{title:'Referenca',matricula:'Registrska',remolque:'Prikolica',empresa:'Podjetje',montador:'Monter',expositor:'Razstavljavec',hall:'Dvorana',stand:'Razstavni prostor',puerta:'Vrata',nombre:'Ime',apellido:'Priimek',pasaporte:'Potni list',telefono:'Telefon',email:'E-pošta',horaIngreso:'Vstop',llamador:'Št. klicatelja',referencia:'Referenca',obs:'Opombe',lista:'Seznam',especial:'Posebno',historial:'Zgodovina',campos:'Polja',estado:'Stanje',tipoVeh:'Tip vozila',descarga:'Razkladanje'},
},

// ── CONDUCTORES ──────────────────────────────────────────
conductores: {
  es:{title:'Conductores',nombre:'Nombre',apellido:'Apellido',pasaporte:'Pasaporte / DNI',telefono:'Teléfono',email:'Email',empresa:'Empresa',pais:'País',fechaNac:'Fecha Nacimiento',activo:'Activo',inactivo:'Inactivo'},
  ca:{title:'Conductors',nombre:'Nom',apellido:'Cognom',pasaporte:'Passaport / DNI',telefono:'Telèfon',email:'Correu',empresa:'Empresa',pais:'País',fechaNac:'Data Naixement',activo:'Actiu',inactivo:'Inactiu'},
  eu:{title:'Gidariak',nombre:'Izena',apellido:'Abizena',pasaporte:'Pasaportea',telefono:'Telefonoa',email:'Emaila',empresa:'Enpresa',pais:'Herrialdea',fechaNac:'Jaiotze data',activo:'Aktiboa',inactivo:'Ez aktiboa'},
  gl:{title:'Condutores',nombre:'Nome',apellido:'Apelido',pasaporte:'Pasaporte / DNI',telefono:'Teléfono',email:'Correo',empresa:'Empresa',pais:'País',fechaNac:'Data Nacemento',activo:'Activo',inactivo:'Inactivo'},
  en:{title:'Drivers',nombre:'First Name',apellido:'Last Name',pasaporte:'Passport / ID',telefono:'Phone',email:'Email',empresa:'Company',pais:'Country',fechaNac:'Date of Birth',activo:'Active',inactivo:'Inactive'},
  fr:{title:'Chauffeurs',nombre:'Prénom',apellido:'Nom',pasaporte:'Passeport',telefono:'Téléphone',email:'Email',empresa:'Société',pais:'Pays',fechaNac:'Date de Naissance',activo:'Actif',inactivo:'Inactif'},
  de:{title:'Fahrer',nombre:'Vorname',apellido:'Nachname',pasaporte:'Reisepass',telefono:'Telefon',email:'Email',empresa:'Firma',pais:'Land',fechaNac:'Geburtsdatum',activo:'Aktiv',inactivo:'Inaktiv'},
  it:{title:'Autisti',nombre:'Nome',apellido:'Cognome',pasaporte:'Passaporto',telefono:'Telefono',email:'Email',empresa:'Azienda',pais:'Paese',fechaNac:'Data di Nascita',activo:'Attivo',inactivo:'Inattivo'},
  pt:{title:'Motoristas',nombre:'Nome',apellido:'Apelido',pasaporte:'Passaporte',telefono:'Telefone',email:'Email',empresa:'Empresa',pais:'País',fechaNac:'Data de Nascimento',activo:'Ativo',inactivo:'Inativo'},
  pl:{title:'Kierowcy',nombre:'Imię',apellido:'Nazwisko',pasaporte:'Paszport',telefono:'Telefon',email:'Email',empresa:'Firma',pais:'Kraj',fechaNac:'Data Urodzenia',activo:'Aktywny',inactivo:'Nieaktywny'},
  ro:{title:'Șoferi',nombre:'Prenume',apellido:'Nume',pasaporte:'Pașaport',telefono:'Telefon',email:'Email',empresa:'Companie',pais:'Țară',fechaNac:'Data Nașterii',activo:'Activ',inactivo:'Inactiv'},
  nl:{title:'Chauffeurs',nombre:'Voornaam',apellido:'Achternaam',pasaporte:'Paspoort',telefono:'Telefoon',email:'Email',empresa:'Bedrijf',pais:'Land',fechaNac:'Geboortedatum',activo:'Actief',inactivo:'Inactief'},
  hu:{title:'Sofőrök',nombre:'Keresztnév',apellido:'Vezetéknév',pasaporte:'Útlevél',telefono:'Telefon',email:'Email',empresa:'Cég',pais:'Ország',fechaNac:'Születési Dátum',activo:'Aktív',inactivo:'Inaktív'},
  cs:{title:'Řidiči',nombre:'Jméno',apellido:'Příjmení',pasaporte:'Pas/OP',telefono:'Telefon',email:'Email',empresa:'Firma',pais:'Země',fechaNac:'Datum narození',activo:'Aktivní',inactivo:'Neaktivní'},
  hr:{title:'Vozači',nombre:'Ime',apellido:'Prezime',pasaporte:'Putovnica',telefono:'Telefon',email:'Email',empresa:'Tvrtka',pais:'Zemlja',fechaNac:'Datum Rođenja',activo:'Aktivan',inactivo:'Neaktivan'},
  uk:{title:'Водії',nombre:'Ім\'я',apellido:'Прізвище',pasaporte:'Паспорт',telefono:'Телефон',email:'Email',empresa:'Компанія',pais:'Країна',fechaNac:'Дата народження',activo:'Активний',inactivo:'Неактивний'},
  ru:{title:'Водители',nombre:'Имя',apellido:'Фамилия',pasaporte:'Паспорт',telefono:'Телефон',email:'Email',empresa:'Компания',pais:'Страна',fechaNac:'Дата рождения',activo:'Активный',inactivo:'Неактивный'},
  tr:{title:'Sürücüler',nombre:'Ad',apellido:'Soyad',pasaporte:'Pasaport',telefono:'Telefon',email:'E-posta',empresa:'Şirket',pais:'Ülke',fechaNac:'Doğum Tarihi',activo:'Aktif',inactivo:'Pasif'},
  ar:{title:'سائقون',nombre:'الاسم',apellido:'اللقب',pasaporte:'جواز سفر',telefono:'هاتف',email:'بريد',empresa:'شركة',pais:'بلد',fechaNac:'تاريخ الميلاد',activo:'نشط',inactivo:'غير نشط'},
  sv:{title:'Förare',nombre:'Förnamn',apellido:'Efternamn',pasaporte:'Pass',telefono:'Telefon',email:'E-post',empresa:'Företag',pais:'Land',fechaNac:'Födelsedatum',activo:'Aktiv',inactivo:'Inaktiv'},
  fi:{title:'Kuljettajat',nombre:'Etunimi',apellido:'Sukunimi',pasaporte:'Passi',telefono:'Puhelin',email:'Sähköposti',empresa:'Yritys',pais:'Maa',fechaNac:'Syntymäaika',activo:'Aktiivinen',inactivo:'Ei aktiivinen'},
  el:{title:'Οδηγοί',nombre:'Όνομα',apellido:'Επώνυμο',pasaporte:'Διαβατήριο',telefono:'Τηλέφωνο',email:'Email',empresa:'Εταιρεία',pais:'Χώρα',fechaNac:'Ημ. Γέννησης',activo:'Ενεργός',inactivo:'Ανενεργός'},
  bg:{title:'Шофьори',nombre:'Име',apellido:'Фамилия',pasaporte:'Паспорт',telefono:'Телефон',email:'Имейл',empresa:'Фирма',pais:'Държава',fechaNac:'Дата на раждане',activo:'Активен',inactivo:'Неактивен'},
  sk:{title:'Vodiči',nombre:'Meno',apellido:'Priezvisko',pasaporte:'Pas/OP',telefono:'Telefón',email:'Email',empresa:'Firma',pais:'Krajina',fechaNac:'Dátum narodenia',activo:'Aktívny',inactivo:'Neaktívny'},
  sl:{title:'Vozniki',nombre:'Ime',apellido:'Priimek',pasaporte:'Potni list',telefono:'Telefon',email:'E-pošta',empresa:'Podjetje',pais:'Država',fechaNac:'Datum rojstva',activo:'Aktiven',inactivo:'Neaktiven'},
},

// ── AGENDA ───────────────────────────────────────────────
agenda: {
  es:{title:'Agenda',fecha:'Fecha',hora:'Hora',empresa:'Empresa',vehiculo:'Vehículo',hall:'Hall',stand:'Stand',estado:'Estado',planificado:'Planificado',enCurso:'En curso',completado:'Completado',cancelado:'Cancelado'},
  ca:{title:'Agenda',fecha:'Data',hora:'Hora',empresa:'Empresa',vehiculo:'Vehicle',hall:'Hall',stand:'Stand',estado:'Estat',planificado:'Planificat',enCurso:'En curs',completado:'Completat',cancelado:'Cancel·lat'},
  eu:{title:'Agenda',fecha:'Data',hora:'Ordua',empresa:'Enpresa',vehiculo:'Ibilgailua',hall:'Aretoa',stand:'Standa',estado:'Egoera',planificado:'Planifikatua',enCurso:'Abian',completado:'Osatua',cancelado:'Bertan behera'},
  gl:{title:'Axenda',fecha:'Data',hora:'Hora',empresa:'Empresa',vehiculo:'Vehículo',hall:'Hall',stand:'Stand',estado:'Estado',planificado:'Planificado',enCurso:'En curso',completado:'Completado',cancelado:'Cancelado'},
  en:{title:'Agenda',fecha:'Date',hora:'Time',empresa:'Company',vehiculo:'Vehicle',hall:'Hall',stand:'Stand',estado:'Status',planificado:'Planned',enCurso:'In progress',completado:'Completed',cancelado:'Cancelled'},
  fr:{title:'Agenda',fecha:'Date',hora:'Heure',empresa:'Société',vehiculo:'Véhicule',hall:'Hall',stand:'Stand',estado:'Statut',planificado:'Planifié',enCurso:'En cours',completado:'Terminé',cancelado:'Annulé'},
  de:{title:'Agenda',fecha:'Datum',hora:'Uhrzeit',empresa:'Firma',vehiculo:'Fahrzeug',hall:'Halle',stand:'Stand',estado:'Status',planificado:'Geplant',enCurso:'Laufend',completado:'Abgeschlossen',cancelado:'Storniert'},
  it:{title:'Agenda',fecha:'Data',hora:'Ora',empresa:'Azienda',vehiculo:'Veicolo',hall:'Padiglione',stand:'Stand',estado:'Stato',planificado:'Pianificato',enCurso:'In corso',completado:'Completato',cancelado:'Annullato'},
  pt:{title:'Agenda',fecha:'Data',hora:'Hora',empresa:'Empresa',vehiculo:'Veículo',hall:'Hall',stand:'Stand',estado:'Estado',planificado:'Planeado',enCurso:'Em andamento',completado:'Concluído',cancelado:'Cancelado'},
  pl:{title:'Agenda',fecha:'Data',hora:'Godzina',empresa:'Firma',vehiculo:'Pojazd',hall:'Hala',stand:'Stoisko',estado:'Status',planificado:'Zaplanowane',enCurso:'W toku',completado:'Zakończone',cancelado:'Anulowane'},
  ro:{title:'Agendă',fecha:'Data',hora:'Ora',empresa:'Companie',vehiculo:'Vehicul',hall:'Hală',stand:'Stand',estado:'Stare',planificado:'Planificat',enCurso:'În curs',completado:'Finalizat',cancelado:'Anulat'},
  nl:{title:'Agenda',fecha:'Datum',hora:'Tijd',empresa:'Bedrijf',vehiculo:'Voertuig',hall:'Hal',stand:'Stand',estado:'Status',planificado:'Gepland',enCurso:'Bezig',completado:'Voltooid',cancelado:'Geannuleerd'},
  hu:{title:'Napirend',fecha:'Dátum',hora:'Idő',empresa:'Cég',vehiculo:'Jármű',hall:'Csarnok',stand:'Stand',estado:'Állapot',planificado:'Tervezett',enCurso:'Folyamatban',completado:'Befejezett',cancelado:'Törölve'},
  cs:{title:'Agenda',fecha:'Datum',hora:'Čas',empresa:'Firma',vehiculo:'Vozidlo',hall:'Hala',stand:'Stánek',estado:'Stav',planificado:'Plánováno',enCurso:'Probíhá',completado:'Dokončeno',cancelado:'Zrušeno'},
  hr:{title:'Raspored',fecha:'Datum',hora:'Vrijeme',empresa:'Tvrtka',vehiculo:'Vozilo',hall:'Dvorana',stand:'Štand',estado:'Status',planificado:'Planirano',enCurso:'U tijeku',completado:'Završeno',cancelado:'Otkazano'},
  uk:{title:'Розклад',fecha:'Дата',hora:'Час',empresa:'Компанія',vehiculo:'Транспорт',hall:'Зал',stand:'Стенд',estado:'Статус',planificado:'Заплановано',enCurso:'В процесі',completado:'Завершено',cancelado:'Скасовано'},
  ru:{title:'Расписание',fecha:'Дата',hora:'Время',empresa:'Компания',vehiculo:'Транспорт',hall:'Зал',stand:'Стенд',estado:'Статус',planificado:'Запланировано',enCurso:'В процессе',completado:'Завершено',cancelado:'Отменено'},
  tr:{title:'Ajanda',fecha:'Tarih',hora:'Saat',empresa:'Şirket',vehiculo:'Araç',hall:'Salon',stand:'Stand',estado:'Durum',planificado:'Planlandı',enCurso:'Devam ediyor',completado:'Tamamlandı',cancelado:'İptal'},
  ar:{title:'جدول',fecha:'تاريخ',hora:'وقت',empresa:'شركة',vehiculo:'مركبة',hall:'قاعة',stand:'جناح',estado:'حالة',planificado:'مخطط',enCurso:'قيد التنفيذ',completado:'مكتمل',cancelado:'ملغى'},
  sv:{title:'Agenda',fecha:'Datum',hora:'Tid',empresa:'Företag',vehiculo:'Fordon',hall:'Hall',stand:'Monter',estado:'Status',planificado:'Planerat',enCurso:'Pågående',completado:'Slutfört',cancelado:'Avbokat'},
  fi:{title:'Kalenteri',fecha:'Päivämäärä',hora:'Aika',empresa:'Yritys',vehiculo:'Ajoneuvo',hall:'Halli',stand:'Osasto',estado:'Tila',planificado:'Suunniteltu',enCurso:'Käynnissä',completado:'Valmis',cancelado:'Peruttu'},
  el:{title:'Ατζέντα',fecha:'Ημερομηνία',hora:'Ώρα',empresa:'Εταιρεία',vehiculo:'Όχημα',hall:'Αίθουσα',stand:'Περίπτερο',estado:'Κατάσταση',planificado:'Προγραμματισμένο',enCurso:'Σε εξέλιξη',completado:'Ολοκληρώθηκε',cancelado:'Ακυρώθηκε'},
  bg:{title:'График',fecha:'Дата',hora:'Час',empresa:'Фирма',vehiculo:'Превозно средство',hall:'Зала',stand:'Щанд',estado:'Статус',planificado:'Планирано',enCurso:'В процес',completado:'Завършено',cancelado:'Отменено'},
  sk:{title:'Agenda',fecha:'Dátum',hora:'Čas',empresa:'Firma',vehiculo:'Vozidlo',hall:'Hala',stand:'Stánok',estado:'Stav',planificado:'Plánované',enCurso:'Prebieha',completado:'Dokončené',cancelado:'Zrušené'},
  sl:{title:'Urnik',fecha:'Datum',hora:'Čas',empresa:'Podjetje',vehiculo:'Vozilo',hall:'Dvorana',stand:'Razstavni prostor',estado:'Stanje',planificado:'Načrtovano',enCurso:'V teku',completado:'Zaključeno',cancelado:'Preklicano'},
},

};

// ═══════════════════════════════════════════════════════════
// FUNCIONES
// ═══════════════════════════════════════════════════════════

const FALLBACK_CHAIN = ['en', 'es'];

export function tr(modulo, clave) {
  const lang = AppState.get('currentLang') || 'es';
  const user = AppState.get('currentUser');
  const protectedModules = ['ingresos','ingresos2','flota','conductores','agenda','analytics','vehiculos','auditoria','recintos','usuarios','eventos','papelera','mensajes','impresion','empresas','migracion','dash'];
  if (user && user.tabs && protectedModules.includes(modulo) && !user.tabs.includes(modulo)) return null;
  const modDict = DICT[modulo];
  if (!modDict) return clave;
  if (modDict[lang] && modDict[lang][clave] !== undefined) return modDict[lang][clave];
  for (const fb of FALLBACK_CHAIN) { if (modDict[fb] && modDict[fb][clave] !== undefined) return modDict[fb][clave]; }
  return clave;
}

export function trFree(modulo, clave) {
  const lang = AppState.get('currentLang') || 'es';
  const modDict = DICT[modulo];
  if (!modDict) return clave;
  if (modDict[lang] && modDict[lang][clave] !== undefined) return modDict[lang][clave];
  for (const fb of FALLBACK_CHAIN) { if (modDict[fb] && modDict[fb][clave] !== undefined) return modDict[fb][clave]; }
  return clave;
}

export function detectLang(navLang) {
  const code = (navLang || 'es').split('-')[0].toLowerCase();
  return LANGS_UI.some(l => l.code === code) ? code : 'en';
}

export function getFlag(code) {
  const l = LANGS_UI.find(x => x.code === code);
  return l ? l.flag : '🌐';
}

export function registerDict(modulo, langCode, translations) {
  if (!DICT[modulo]) DICT[modulo] = {};
  DICT[modulo][langCode] = { ...(DICT[modulo][langCode] || {}), ...translations };
}
